# zeros

In [1]:
import numpy as np

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
arr =np. zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

# ones

In [4]:
arr = np.ones((10))
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# eye

In [6]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
arr = np.eye(4,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# digonal fun

In [8]:
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [9]:
rand_arr = np.random.randint(1,15,6)
rand_arr

array([ 2,  9,  9, 13,  3,  7])

In [10]:
rand_arr = np.random.rand(10)# provides value between 0 to 1
rand_arr

array([0.18253546, 0.77812072, 0.39064109, 0.055077  , 0.79009439,
       0.43432813, 0.13578025, 0.52330085, 0.08134182, 0.8028628 ])

In [15]:
rand_arr = np.random.rand(3,3) # o/p between 0---1
rand_arr

array([[0.19312096, 0.83257733, 0.76688335],
       [0.68436409, 0.08372157, 0.90568012],
       [0.04692942, 0.65554357, 0.73432966]])

In [16]:
np.mean(rand_arr)

0.5447944522280808

In [12]:
rand_arr = np.random.randn(20)# centered between - 0 +
rand_arr

array([ 0.17239645,  0.50528606, -0.61488173,  1.91262934, -0.8726056 ,
       -0.44468287,  0.24141687, -0.36145083,  0.30889864,  1.06894123,
       -0.08218599, -0.53329707, -1.57023402, -0.18071684,  0.31839343,
       -0.7539944 ,  0.53449996, -0.44806933, -1.32616487,  0.12156708])

In [13]:
rand_arr = np.random.randn(12337836)# mean will be near to zero
np.mean(rand_arr)

-8.767134279525035e-05

In [14]:
rand_arr = np.random.randn(45422442)# mean will be near to zero
np.mean(rand_arr)

-4.525630175199851e-06