In [1]:
import numpy as np

In [2]:
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)
matrix1

array([[ 5,  5, 16],
       [13, 15,  5],
       [ 1, 15,  2]])

In [3]:
matrix2

array([[22, 29, 21],
       [33, 21, 26],
       [36, 38, 21]])

# horizental stacking

In [4]:
np.hstack((matrix1,matrix2))

array([[ 5,  5, 16, 22, 29, 21],
       [13, 15,  5, 33, 21, 26],
       [ 1, 15,  2, 36, 38, 21]])

# vertical stacking

In [5]:
np.vstack((matrix1,matrix2))

array([[ 5,  5, 16],
       [13, 15,  5],
       [ 1, 15,  2],
       [22, 29, 21],
       [33, 21, 26],
       [36, 38, 21]])

In [6]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
np.stack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [8]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])