In [1]:
import numpy as np

# two bracket notation

In [3]:
matrix = np.array ([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
matrix [0][2]

15

In [5]:
matrix[1][1]

25

In [6]:
matrix [-2][-1]

30

# single bracket notation

In [7]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
matrix[0,1]

10

In [9]:
matrix[2,2]

45

In [10]:
matrix[1,1]

25

In [11]:
matrix[2,1]

40

In [12]:
matrix[1,0]

20

# slicing using single bracket notation

In [13]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
matrix[:,:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
matrix[0:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [16]:
matrix[1:2,1:]

array([[25, 30]])

In [17]:
matrix[:,2:]

array([[15],
       [30],
       [45]])

In [18]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
matrix[1:,:2]

array([[20, 25],
       [35, 40]])

In [20]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
matrix[1:2,:2]

array([[20, 25]])

In [22]:
matrix[1:,1:]

array([[25, 30],
       [40, 45]])

In [23]:
matrix2 = np.random.randint(1,101,80).reshape(8,10)
matrix2

array([[ 38,  45,  25,  38,   6,  69,  68,  38,   9,  53],
       [ 91,  41,  65,  20,  69,  99,  93,  31,  86,  61],
       [ 28,  19,  75,  86,   1,  36,  72,  20,  34,  22],
       [  2,   1,  52,  86,   9,   7,  71,  79,  54,  45],
       [ 17,  77,  14,   5,  89,  90,  18,  44,  19,  38],
       [ 10,  77,   2,  50,  45,  75,  87,  78,  34,  29],
       [ 33,  85,  65,  90,  74,  40,  70,  87,  58,  93],
       [ 96, 100,  13,  43,  78,  27,   4,  16,  31,  75]])

In [24]:
matrix2[4:,6:]

array([[18, 44, 19, 38],
       [87, 78, 34, 29],
       [70, 87, 58, 93],
       [ 4, 16, 31, 75]])

In [25]:
matrix2[4:,4:7]

array([[89, 90, 18],
       [45, 75, 87],
       [74, 40, 70],
       [78, 27,  4]])

In [26]:
matrix2[0:3,3:6]

array([[38,  6, 69],
       [20, 69, 99],
       [86,  1, 36]])

In [27]:
matrix2[3:7,0:5]

array([[ 2,  1, 52, 86,  9],
       [17, 77, 14,  5, 89],
       [10, 77,  2, 50, 45],
       [33, 85, 65, 90, 74]])