# 1. Import the numpy package under the name

In [27]:
import numpy as np

# 2. Print the numpy version and the configuration 

In [33]:
print("NumPy Version : ",np.__version__)
print(np.show_config())

NumPy Version :  1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None),

# 3. Create a null vector of size 10

In [6]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4. How to find the memory size of any array

In [32]:
v = np.array([1,5,6,4,3])
print("Memory size of numpy array in bytes:",
      v.size * v.itemsize)

Memory size of numpy array in bytes: 20


# 5. Reverse a vector (first element becomes last)

In [25]:
v = np.array([1,5,6,4,3])
np.flip(v)

array([3, 4, 6, 5, 1])

# 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
matrix = np.random.randint(0,8,9).reshape(3,3)
matrix

array([[4, 3, 3],
       [0, 4, 0],
       [6, 4, 5]])

# 7. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [8]:
v2 = np.array([1,2,0,0,4,0])
np.where(v2 != 0)

(array([0, 1, 4], dtype=int64),)

# 8. Create a 3x3 identity matrix

In [10]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 9. Create a 3x3x3 array with random values 

In [11]:
a1 = np.random.randint(0,100,27).reshape(3,3,3)
a1

array([[[18, 39, 11],
        [60, 85, 83],
        [81,  6, 76]],

       [[ 7, 67, 94],
        [88, 32, 33],
        [90, 89, 40]],

       [[60, 40, 23],
        [ 9, 84, 21],
        [82, 12, 86]]])

# 10.Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
a2 = np.random.randint(0,100,100).reshape(10,10)
print(a2)
print(np.min(a2))
print(np.max(a2))

[[62 84  1 52 44 72 90 17 78 82]
 [76 78 44 96 58 65 80 10 98 91]
 [12  3 68 29  0 64 83 54 55 11]
 [15 54 34 66 91 17 20 33 78 63]
 [69 44 65  0 31  9 89 25  0 72]
 [15  0 62 91 51 18 67 64 51 31]
 [ 3 33 67  4 51 64 15 57 44 53]
 [17 59 27  8 24 26 75 41 32 16]
 [10  7 68 15 81 49 61 95 16 46]
 [85 16 54 86 17 73 86 46 56 72]]
0
98


# 11. Create a random vector of size 30 and find the mean value

In [21]:
a3 = np.random.randint(0,10,30)
print(a3)
np.mean(a3)

[2 1 6 7 7 7 8 4 6 6 9 6 9 0 4 8 8 2 0 5 9 5 8 3 9 9 8 8 4 8]


5.866666666666666

# 12.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [23]:
d1 = np.tril(np.random.randint(1,5,25).reshape(5,5))
d1

array([[2, 0, 0, 0, 0],
       [2, 2, 0, 0, 0],
       [2, 4, 2, 0, 0],
       [4, 1, 3, 2, 0],
       [3, 2, 3, 1, 4]])

# 13.How to find common values between two arrays?

In [20]:
a4 = np.array([1,2,3,4,5])
a5 = np.array([4,5,6,7,8])
np.intersect1d(a4,a5)

array([4, 5])

# 14. Create a random vector of size 10 and sort it

In [17]:
r = np.random.randint(0,10,10)
np.sort(r)

array([3, 3, 3, 4, 4, 5, 7, 8, 9, 9])