In [1]:
import numpy as np

In [2]:
matrix= np.random.randint(1,11,9).reshape(3,3)
matrix

array([[10,  7,  7],
       [ 1,  4,  2],
       [ 3,  2,  4]])

In [3]:
np.sum(matrix)

40

In [4]:
matrix.sum

<function ndarray.sum>

In [8]:
np.mean(matrix)

4.444444444444445

In [5]:
np.min(matrix)

1

In [6]:
np.max(matrix)

10

In [7]:
np.mean(matrix,axis=1)# 1 -Row wise & 0 - Colm

array([8.        , 2.33333333, 3.        ])

In [9]:
np.min(matrix,axis=1)

array([7, 1, 2])

In [10]:
np.max(matrix,axis=1)

array([10,  4,  4])

In [11]:
np.max(matrix,axis=0)

array([10,  7,  7])

In [12]:
np.sum(matrix ,axis=1)

array([24,  7,  9])

# cumulative sum

In [13]:
np.cumsum(matrix,axis=1)

array([[10, 17, 24],
       [ 1,  5,  7],
       [ 3,  5,  9]])

In [14]:
np.cumsum(matrix,axis=0)

array([[10,  7,  7],
       [11, 11,  9],
       [14, 13, 13]])

In [15]:
np.prod(matrix,axis=0) # 3*3*7=63

array([30, 56, 56])