# rand fun

In [1]:
import numpy as np

In [9]:
rand_arr = np.random.randint(11,25,20)
rand_arr 

array([16, 13, 11, 24, 13, 20, 23, 17, 23, 15, 15, 19, 13, 17, 11, 18, 20,
       17, 22, 20])

In [11]:
rand_arr = np.random.rand(7)
rand_arr 

array([0.0442031 , 0.60700324, 0.94678871, 0.50611151, 0.61242478,
       0.95702818, 0.17441212])

In [12]:
rand_arr = np.random.randint(1,10,5)
rand_arr 

array([9, 5, 3, 2, 1])

In [13]:
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.76380402, 0.7701322 , 0.79139709],
       [0.22632406, 0.02518143, 0.52812168]])

# radn fun

In [18]:
rand_arr = np.random.randn(20)#It provides values inbetween +_0 to 1
rand_arr 

array([ 1.80960655, -0.016069  ,  0.43778881, -1.71507355,  1.33687764,
       -0.7528055 ,  1.1332724 ,  0.76240971, -1.3692662 ,  0.45669891,
       -1.73024039, -0.74598606,  1.03882565, -0.60678672, -1.2251093 ,
        0.80556676, -0.51564346,  0.37440177,  1.0061816 ,  0.08184707])