In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,100,20)
arr

array([37, 49, 89, 34, 42, 41, 88, 89, 79, 28, 34, 57, 95,  8, 57, 13, 10,
       93, 56, 97])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(20,)

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr1 = np.random.randint(1,100,20).reshape(2,10)
arr1

array([[94, 10, 13,  9, 43, 23, 84, 97, 44, 50],
       [50, 73, 94, 17, 97, 47, 54, 58, 18, 64]])

In [7]:
arr2 = np.random.randint(1,20,10)
arr2 = arr2.reshape(2,5)
print(arr2)



[[15 12 16  8  9]
 [11  1 15 10  2]]


In [8]:

arr = np.random.randint(1,100,50).reshape(5,10)
arr

array([[30, 71, 14, 78, 73, 18,  2, 39, 62, 96],
       [19, 75, 47, 17, 34, 76, 64, 94,  8, 11],
       [86, 40, 75, 77, 53, 30, 28, 84, 66,  7],
       [56, 51, 10, 80, 21, 26, 35, 33, 33, 75],
       [57, 63, 56,  2, 53, 36, 22, 18, 55,  1]])

In [9]:
arr.ndim

2

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.shape

(5, 10)

In [12]:
arr =np.array((1,11,12))
arr

array([ 1, 11, 12])

In [13]:
arr5 = np.arange (1,11)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr2 = arr5.reshape(2,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
arr2.ndim

2

In [16]:
arr2.size

10

In [17]:
arr2.shape

(2, 5)

In [18]:
arr5.dtype

dtype('int32')